services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    labels:
      io.github.devynspencer.group: "monitoring"
      io.github.devynspencer.description: "Prometheus monitoring system"
      io.github.devynspencer.source: https://github.com/devynspencer/docker-home-network
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    labels:
      io.github.devynspencer.group: "monitoring"
      io.github.devynspencer.description: "Grafana dashboard service"
      io.github.devynspencer.source: https://github.com/devynspencer/docker-home-network
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources

volumes:
  prometheus-data:
